version: '3'
services:
    web:
        image: nginx:alpine
        container_name: ${PREFIX}web
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "../:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8080:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php
            - mysqldb
    php:
        build: ./php
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../src:/var/www/html"
            - "./etc/.gitconfig:/var/www/.gitconfig"
            - "./etc/.bashrc:/var/www/.bashrc"
            - "./etc/.gitignore_global:/var/www/.gitignore_global"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PREFIX}pa
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysqldb
#        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"